menu:
- {name: 'Official Stuff', url: '/courses/BST236ComputingI'}
- {name: 'Blog', url: '/blog'}
- {name: 'Stonks', url: '/stocks'}
- {name: 'Contact', url: '/contact'}
- {name: 'Homers', url: '/homers'}

